<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dt_penduduk_model extends CI_Model
{

    public $table = 'dt_penduduk';
    public $id = 'id_penduduk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_penduduk,no_kk,nik,nama,alamat,jenis_kelamin,tempat_lahir,tgl_lahir,agama,pendidikan,pekerjaan,gol_darah,stts_perkawinan,no_hp');
        $this->datatables->from('dt_penduduk');
        //add this line for join
        //$this->datatables->join('table2', 'dt_penduduk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('dt_penduduk/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('dt_penduduk/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_penduduk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penduduk', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('stts_perkawinan', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penduduk', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('pendidikan', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('stts_perkawinan', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dt_penduduk_model.php */
/* Location: ./application/models/Dt_penduduk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-25 08:12:20 */
/* http://harviacode.com */