<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_kk_model extends CI_Model
{

    public $table = 'tbl_kk';
    public $id = 'id_kk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_kk,tgl_input_kk,kepala_keluarga,imagekk1,imagekk2,imagekk3,dt_penduduk.id_penduduk,nama,no_kk,nik,jenis_kelamin,tempat_lahir,tgl_lahir,agama,pendidikan,pekerjaan,gol_darah,alamat');
        $this->datatables->from('tbl_kk');
        //add this line for join
        $this->datatables->join('dt_penduduk', 'tbl_kk.id_penduduk = dt_penduduk.id_penduduk');
        $this->datatables->add_column('action', anchor(site_url('tbl_kk/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('tbl_kk/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_kk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->datatables->select('id_kk,tgl_input_kk,kepala_keluarga,imagekk1,imagekk2,imagekk3,dt_penduduk.id_penduduk,nama,no_kk,nik,jenis_kelamin,tempat_lahir,tgl_lahir,agama,pendidikan,pekerjaan,gol_darah,alamat');
        $this->datatables->join('dt_penduduk', 'tbl_kk.id_penduduk = dt_penduduk.id_penduduk');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_bulan($bulan,$tahun)
    {
        $this->datatables->select('id_kk,tgl_input_kk,kepala_keluarga,imagekk1,imagekk2,imagekk3,dt_penduduk.id_penduduk,nama,no_kk,nik,jenis_kelamin,tempat_lahir,tgl_lahir,agama,pendidikan,pekerjaan,gol_darah,alamat');
        $this->datatables->join('dt_penduduk', 'tbl_kk.id_penduduk = dt_penduduk.id_penduduk');
        $this->db->where('MONTH(tgl_input_kk)', $bulan);
        $this->db->where('YEAR(tgl_input_kk)', $tahun);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->datatables->select('id_kk,tgl_input_kk,kepala_keluarga,imagekk1,imagekk2,imagekk3,dt_penduduk.id_penduduk,nama,no_kk,nik,jenis_kelamin,tempat_lahir,tgl_lahir,agama,pendidikan,pekerjaan,gol_darah,alamat');
        $this->datatables->join('dt_penduduk', 'tbl_kk.id_penduduk = dt_penduduk.id_penduduk');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kk', $q);
	$this->db->or_like('tgl_input_kk', $q);
	$this->db->or_like('id_penduduk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kk', $q);
	$this->db->or_like('tgl_input_kk', $q);
	$this->db->or_like('id_penduduk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_kk_model.php */
/* Location: ./application/models/Tbl_kk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-27 12:35:54 */
/* http://harviacode.com */